server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:h2:mem:drones
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

